#!/bin/bash

# 脚本名称: ColorGenerate.sh
# 功能: 根据 JSON 配置文件生成 UIColor+TDDExtension.swift
# 用法: ./ColorGenerate.sh [json-file] [output-file]
# 用法二: sh ColorGenerate.sh
# 注意：JSON 文件规范 请参考 TopDonDiag/Classes/TopdonDiagnosis.bundle/Theme.json

# 设置默认路径
CUR_DIR=$PWD
DEFAULT_JSON="$CUR_DIR/TopDonDiag/Classes/TopdonDiagnosis.bundle/Theme.json"
DEFAULT_SWIFT="$CUR_DIR/TopDonDiag/Classes/Tools/Category/UIColor+TDDExtension.swift"

# 处理输入参数
if [ $# -ge 1 ]; then
    JSON_FILE=$1
else
    JSON_FILE=$DEFAULT_JSON
fi

if [ $# -ge 2 ]; then
    OUTPUT_FILE=$2
else
    OUTPUT_FILE=$DEFAULT_SWIFT
fi

# 确保输出目录存在
mkdir -p "$(dirname "$SWIFT_FILE")"

# 创建输出文件头部
cat > "$OUTPUT_FILE" <<EOF
//
//  UIColor+TDDExtension.swift
//  TopdonDiagnosis
//
//  Generated by script <ColorGenerate.sh> on $(date +%Y/%m/%d).
//

import Foundation
import TDBasis
import TDTheme
import TDUIProvider

fileprivate protocol JSONKey {
    static var keypath: String { get }
}
extension JSONKey {
    static func keypath(for name: String) -> String {
        if name.hasPrefix(keypath) {
            return name
        }
        return keypath + "." + name
    }
    
    static func color(with keyName: String) -> UIColor? {
        themeColor(with: keypath(for: keyName))?.color ?? .clear
    }
    
    static func themeColor(with keyName: String) -> ThemeColorPicker? {
        UIConfig.color(with: keypath(for: keyName), middlewareKey: middleKey) ?? .clear
    }
    
    static func gradientOrNormal(key: String, size: CGSize) -> ThemeColorPicker? {
        let colorKey = keypath(for: key) + ".color"
        
        let normalColor = themeColor(with: colorKey)
        
        guard let gradientColor = gradient(key: key, size: size) else {
            return normalColor
        }
        
        return gradientColor
    }
    
    static func gradient(key: String, size: CGSize) -> ThemeColorPicker? {
        let gradientColorsKey = keypath(for: key) + ".gradientColors"
        let gradientStyleKey = keypath(for: key) + ".gradientStyle"
        guard let colors = UIConfig.gradient(keyPath: gradientColorsKey, middlewareKey: middleKey),
              let style = UIConfig.gradientStyle(with: gradientStyleKey, middlewareKey: middleKey)
        else {
            return nil
        }
        
        let color = UIColor.td.gradient(colors: colors, size: size, style: style)
        return ThemeColorPicker(v: { color } )
    }
}
//MARK: - JSON key 路径
extension TDD_UIProvider {
EOF

# 生成模块结构体
jq -r '.TopdonDiagnosis | keys_unsorted[]' "$JSON_FILE" | while read -r module; do
    capitalized=$(echo "$module" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
    echo "    public struct $capitalized: JSONKey { static var keypath: String {\"TopdonDiagnosis.$module\"} }"
done >> "$OUTPUT_FILE"

echo "}" >> "$OUTPUT_FILE"

# 生成颜色扩展
jq -r '.TopdonDiagnosis | keys_unsorted[]' "$JSON_FILE" | while read -r module; do
    capitalized=$(echo "$module" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
    
    echo ""
    echo "//MARK: - $capitalized 颜色配置"
    echo "public extension TDD_UIProvider.$capitalized {"
    
    jq -r ".TopdonDiagnosis.$module | keys_unsorted[]" "$JSON_FILE" | while read -r key; do
        value_type=$(jq -r ".TopdonDiagnosis.$module.$key | type" "$JSON_FILE")
        
        if [ "$value_type" = "string" ]; then
            # 处理纯色值
            echo "    static var $key: ThemeColorPicker? { themeColor(with: \"$key\") }"
        elif [ "$value_type" = "object" ]; then
            # 处理渐变/混合类型
            echo "    static var $key: ThemeColorPicker? { themeColor(with: \"$key.color\") }"
            echo "    static func $key(size: CGSize) -> ThemeColorPicker? {"
            echo "        gradientOrNormal(key: \"$key\", size: size)"
            echo "    }"
        fi
    done
    
    echo "}"
done >> "$OUTPUT_FILE"

# 生成UIColor扩展
echo "" >> "$OUTPUT_FILE"
echo "// MARK: - UIColor Convenience Accessors" >> "$OUTPUT_FILE"
echo "public extension UIColor {" >> "$OUTPUT_FILE"

jq -r '.TopdonDiagnosis | keys_unsorted[]' "$JSON_FILE" | while read -r module; do
    echo "    "
    echo "    // ${module} 相关属性"
    jq -r ".TopdonDiagnosis.$module | keys_unsorted[]" "$JSON_FILE" | while read -r key; do
        prefix="tdd_${module}_$key"
        
        # 获取值的类型
        value_type=$(jq -r ".TopdonDiagnosis.$module.$key | type" "$JSON_FILE")
        
        if [ "$value_type" = "object" ]; then
            # 生成带 size 参数的函数
            echo "    @objc static func $prefix(size: CGSize) -> UIColor? {"
            echo "        TDD_UIProvider.${module}.$key(size: size)?.color"
            echo "    }"
        fi
        
        # 始终生成属性访问器
        echo "    @objc static var $prefix: UIColor? { TDD_UIProvider.${module}.$key?.color }"
    done
done >> "$OUTPUT_FILE"

echo "}" >> "$OUTPUT_FILE"

# 生成ThemeColorPicker扩展
echo "" >> "$OUTPUT_FILE"
echo "// MARK: - ThemeColorPicker Convenience Accessors" >> "$OUTPUT_FILE"
echo "public extension ThemeColorPicker {" >> "$OUTPUT_FILE"

jq -r '.TopdonDiagnosis | keys_unsorted[]' "$JSON_FILE" | while read -r module; do
    echo "    "
    echo "    // ${module} 相关属性"
    jq -r ".TopdonDiagnosis.$module | keys_unsorted[]" "$JSON_FILE" | while read -r key; do
        prefix="tdd_${module}_$key"
        
        # 获取值的类型
        value_type=$(jq -r ".TopdonDiagnosis.$module.$key | type" "$JSON_FILE")
        
        if [ "$value_type" = "object" ]; then
            # 生成带 size 参数的函数
            echo "    static func $prefix(size: CGSize) -> ThemeColorPicker? {"
            echo "        TDD_UIProvider.${module}.$key(size: size)"
            echo "    }"
        fi
        
        # 始终生成属性访问器
        echo "    static var $prefix: ThemeColorPicker? { TDD_UIProvider.${module}.$key }"
    done
done >> "$OUTPUT_FILE"

echo "}" >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE successfully"
