//
//  UIColor+TDDExtension.swift
//  TopdonDiagnosis
//
//  Generated by script <ColorGenerate.sh> on 2025/10/16.
//

import Foundation
import TDBasis
import TDTheme
import TDUIProvider

fileprivate protocol JSONKey {
    static var keypath: String { get }
}
extension JSONKey {
    static func keypath(for name: String) -> String {
        if name.hasPrefix(keypath) {
            return name
        }
        return keypath + "." + name
    }
    
    static func color(with keyName: String) -> UIColor? {
        themeColor(with: keypath(for: keyName))?.color ?? .clear
    }
    
    static func themeColor(with keyName: String) -> ThemeColorPicker? {
        UIConfig.color(with: keypath(for: keyName), middlewareKey: middleKey) ?? .clear
    }
    
    static func gradientOrNormal(key: String, size: CGSize) -> ThemeColorPicker? {
        let colorKey = keypath(for: key) + ".color"
        
        let normalColor = themeColor(with: colorKey)
        
        guard let gradientColor = gradient(key: key, size: size) else {
            return normalColor
        }
        
        return gradientColor
    }
    
    static func gradient(key: String, size: CGSize) -> ThemeColorPicker? {
        let gradientColorsKey = keypath(for: key) + ".gradientColors"
        let gradientStyleKey = keypath(for: key) + ".gradientStyle"
        guard let colors = UIConfig.gradient(keyPath: gradientColorsKey, middlewareKey: middleKey),
              let style = UIConfig.gradientStyle(with: gradientStyleKey, middlewareKey: middleKey)
        else {
            return nil
        }
        
        let color = UIColor.td.gradient(colors: colors, size: size, style: style)
        return ThemeColorPicker(v: { color } )
    }
}
//MARK: - JSON key 路径
extension TDD_UIProvider {
    public struct General: JSONKey { static var keypath: String {"TopdonDiagnosis.General"} }
    public struct MsgProgress: JSONKey { static var keypath: String {"TopdonDiagnosis.MsgProgress"} }
    public struct TopView: JSONKey { static var keypath: String {"TopdonDiagnosis.TopView"} }
    public struct BottomView: JSONKey { static var keypath: String {"TopdonDiagnosis.BottomView"} }
    public struct Report: JSONKey { static var keypath: String {"TopdonDiagnosis.Report"} }
    public struct SystemScan: JSONKey { static var keypath: String {"TopdonDiagnosis.SystemScan"} }
    public struct List: JSONKey { static var keypath: String {"TopdonDiagnosis.List"} }
    public struct LiveData: JSONKey { static var keypath: String {"TopdonDiagnosis.LiveData"} }
    public struct DTC: JSONKey { static var keypath: String {"TopdonDiagnosis.DTC"} }
    public struct Keyboard: JSONKey { static var keypath: String {"TopdonDiagnosis.Keyboard"} }
    public struct Menu: JSONKey { static var keypath: String {"TopdonDiagnosis.Menu"} }
    public struct Popup: JSONKey { static var keypath: String {"TopdonDiagnosis.Popup"} }
    public struct Input: JSONKey { static var keypath: String {"TopdonDiagnosis.Input"} }
    public struct Trouble: JSONKey { static var keypath: String {"TopdonDiagnosis.Trouble"} }
    public struct FCA: JSONKey { static var keypath: String {"TopdonDiagnosis.FCA"} }
    public struct Alert: JSONKey { static var keypath: String {"TopdonDiagnosis.Alert"} }
    public struct Loading: JSONKey { static var keypath: String {"TopdonDiagnosis.Loading"} }
}

//MARK: - General 颜色配置
public extension TDD_UIProvider.General {
    static var line: ThemeColorPicker? { themeColor(with: "line") }
    static var viewBorder: ThemeColorPicker? { themeColor(with: "viewBorder") }
    static var cardBackground: ThemeColorPicker? { themeColor(with: "cardBackground") }
    static var buttonBackground: ThemeColorPicker? { themeColor(with: "buttonBackground") }
    static var dashLine: ThemeColorPicker? { themeColor(with: "dashLine") }
    static var shadowBackground: ThemeColorPicker? { themeColor(with: "shadowBackground") }
    static var webLinkText: ThemeColorPicker? { themeColor(with: "webLinkText") }
    static var cellHeadBackground: ThemeColorPicker? { themeColor(with: "cellHeadBackground") }
    static var cellBackground: ThemeColorPicker? { themeColor(with: "cellBackground") }
    static var textFieldBackground: ThemeColorPicker? { themeColor(with: "textFieldBackground") }
    static var textFieldClearButtonTint: ThemeColorPicker? { themeColor(with: "textFieldClearButtonTint") }
    static var titleLock: ThemeColorPicker? { themeColor(with: "titleLock") }
    static var placeholderText: ThemeColorPicker? { themeColor(with: "placeholderText") }
    static var diagBlue: ThemeColorPicker? { themeColor(with: "diagBlue") }
    static var collectionViewBackground: ThemeColorPicker? { themeColor(with: "collectionViewBackground") }
}

//MARK: - MsgProgress 颜色配置
public extension TDD_UIProvider.MsgProgress {
    static var titleText: ThemeColorPicker? { themeColor(with: "titleText") }
    static var trackTint: ThemeColorPicker? { themeColor(with: "trackTint") }
    static var progressTint: ThemeColorPicker? { themeColor(with: "progressTint.color") }
    static func progressTint(size: CGSize) -> ThemeColorPicker? {
        gradientOrNormal(key: "progressTint", size: size)
    }
}

//MARK: - TopView 颜色配置
public extension TDD_UIProvider.TopView {
    static var tipsBackground: ThemeColorPicker? { themeColor(with: "tipsBackground") }
    static var tipsText: ThemeColorPicker? { themeColor(with: "tipsText") }
}

//MARK: - BottomView 颜色配置
public extension TDD_UIProvider.BottomView {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var tipsBackground: ThemeColorPicker? { themeColor(with: "tipsBackground") }
    static var tipsText: ThemeColorPicker? { themeColor(with: "tipsText") }
    static var buttonNormalBackground: ThemeColorPicker? { themeColor(with: "buttonNormalBackground") }
    static var buttonDisableBackground: ThemeColorPicker? { themeColor(with: "buttonDisableBackground") }
    static var buttonHighlightBackground: ThemeColorPicker? { themeColor(with: "buttonHighlightBackground") }
    static var buttonNormalText: ThemeColorPicker? { themeColor(with: "buttonNormalText") }
    static var buttonDisableText: ThemeColorPicker? { themeColor(with: "buttonDisableText") }
}

//MARK: - Report 颜色配置
public extension TDD_UIProvider.Report {
    static var inputNormalCellBackground: ThemeColorPicker? { themeColor(with: "inputNormalCellBackground") }
    static var codeSectionText: ThemeColorPicker? { themeColor(with: "codeSectionText") }
    static var codeSectionBackground: ThemeColorPicker? { themeColor(with: "codeSectionBackground") }
    static var codeTitleText: ThemeColorPicker? { themeColor(with: "codeTitleText") }
    static var infoValueText: ThemeColorPicker? { themeColor(with: "infoValueText") }
    static var repairHeaderText: ThemeColorPicker? { themeColor(with: "repairHeaderText") }
    static var repairSectionPDFLine: ThemeColorPicker? { themeColor(with: "repairSectionPDFLine") }
    static var summaryBackground: ThemeColorPicker? { themeColor(with: "summaryBackground") }
    static var summaryPDFBackground: ThemeColorPicker? { themeColor(with: "summaryPDFBackground") }
    static var summaryBottomLine: ThemeColorPicker? { themeColor(with: "summaryBottomLine") }
    static var summaryTipsText: ThemeColorPicker? { themeColor(with: "summaryTipsText") }
    static var mileSelectBackground: ThemeColorPicker? { themeColor(with: "mileSelectBackground") }
    static var mileNormalBackground: ThemeColorPicker? { themeColor(with: "mileNormalBackground") }
    static var headCellBackground: ThemeColorPicker? { themeColor(with: "headCellBackground") }
    static var disclaimText: ThemeColorPicker? { themeColor(with: "disclaimText") }
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var PDFBackground: ThemeColorPicker? { themeColor(with: "PDFBackground") }
}

//MARK: - SystemScan 颜色配置
public extension TDD_UIProvider.SystemScan {
    static var viewBackground: ThemeColorPicker? { themeColor(with: "viewBackground") }
    static var cellBackground: ThemeColorPicker? { themeColor(with: "cellBackground") }
    static var line: ThemeColorPicker? { themeColor(with: "line") }
    static var cellHighlightBackground: ThemeColorPicker? { themeColor(with: "cellHighlightBackground.color") }
    static func cellHighlightBackground(size: CGSize) -> ThemeColorPicker? {
        gradientOrNormal(key: "cellHighlightBackground", size: size)
    }
}

//MARK: - List 颜色配置
public extension TDD_UIProvider.List {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var cellSelectBackground: ThemeColorPicker? { themeColor(with: "cellSelectBackground.color") }
    static func cellSelectBackground(size: CGSize) -> ThemeColorPicker? {
        gradientOrNormal(key: "cellSelectBackground", size: size)
    }
    static var cellHighlightBackground: ThemeColorPicker? { themeColor(with: "cellHighlightBackground.color") }
    static func cellHighlightBackground(size: CGSize) -> ThemeColorPicker? {
        gradientOrNormal(key: "cellHighlightBackground", size: size)
    }
}

//MARK: - LiveData 颜色配置
public extension TDD_UIProvider.LiveData {
    static var cellBackground: ThemeColorPicker? { themeColor(with: "cellBackground") }
    static var sepLine: ThemeColorPicker? { themeColor(with: "sepLine") }
    static var valueNormalText: ThemeColorPicker? { themeColor(with: "valueNormalText") }
    static var unitNormalText: ThemeColorPicker? { themeColor(with: "unitNormalText") }
    static var segmentBackground: ThemeColorPicker? { themeColor(with: "segmentBackground") }
    static var recordBackground: ThemeColorPicker? { themeColor(with: "recordBackground") }
    static var scoreText: ThemeColorPicker? { themeColor(with: "scoreText") }
    static var setBackground: ThemeColorPicker? { themeColor(with: "setBackground") }
    static var setRangeText: ThemeColorPicker? { themeColor(with: "setRangeText") }
    static var setRangeBackground: ThemeColorPicker? { themeColor(with: "setRangeBackground") }
    static var legendText: ThemeColorPicker? { themeColor(with: "legendText") }
}

//MARK: - DTC 颜色配置
public extension TDD_UIProvider.DTC {
    static var fault: ThemeColorPicker? { themeColor(with: "fault") }
    static var noFault: ThemeColorPicker? { themeColor(with: "noFault") }
    static var statusNormal: ThemeColorPicker? { themeColor(with: "statusNormal") }
    static var pdfStatsuNormal: ThemeColorPicker? { themeColor(with: "pdfStatsuNormal") }
    static var pdfNormal: ThemeColorPicker? { themeColor(with: "pdfNormal") }
}

//MARK: - Keyboard 颜色配置
public extension TDD_UIProvider.Keyboard {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var itemDisableBackground: ThemeColorPicker? { themeColor(with: "itemDisableBackground") }
    static var itemNormalBackground: ThemeColorPicker? { themeColor(with: "itemNormalBackground") }
    static var itemHighlightBackground: ThemeColorPicker? { themeColor(with: "itemHighlightBackground") }
    static var itemNormalText: ThemeColorPicker? { themeColor(with: "itemNormalText") }
    static var itemHighlightBorder: ThemeColorPicker? { themeColor(with: "itemHighlightBorder") }
    static var itemDisableText: ThemeColorPicker? { themeColor(with: "itemDisableText") }
    static var enterBackground: ThemeColorPicker? { themeColor(with: "enterBackground") }
    static var deleteBackground: ThemeColorPicker? { themeColor(with: "deleteBackground") }
}

//MARK: - Menu 颜色配置
public extension TDD_UIProvider.Menu {
    static var cellBackground: ThemeColorPicker? { themeColor(with: "cellBackground") }
    static var cellBackgroundGradientStyle: ThemeColorPicker? { themeColor(with: "cellBackgroundGradientStyle") }
    static var cellBackgroundGradientColors: ThemeColorPicker? { themeColor(with: "cellBackgroundGradientColors") }
    static var cellHighlightBackground: ThemeColorPicker? { themeColor(with: "cellHighlightBackground") }
    static var textDisable: ThemeColorPicker? { themeColor(with: "textDisable") }
}

//MARK: - Popup 颜色配置
public extension TDD_UIProvider.Popup {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
}

//MARK: - Input 颜色配置
public extension TDD_UIProvider.Input {
    static var historyCellBackground: ThemeColorPicker? { themeColor(with: "historyCellBackground") }
    static var textViewBackground: ThemeColorPicker? { themeColor(with: "textViewBackground") }
}

//MARK: - Trouble 颜色配置
public extension TDD_UIProvider.Trouble {
    static var showStateBackground: ThemeColorPicker? { themeColor(with: "showStateBackground") }
    static var background: ThemeColorPicker? { themeColor(with: "background") }
}

//MARK: - FCA 颜色配置
public extension TDD_UIProvider.FCA {
    static var areaBackground: ThemeColorPicker? { themeColor(with: "areaBackground") }
}

//MARK: - Alert 颜色配置
public extension TDD_UIProvider.Alert {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var confirmBackground: ThemeColorPicker? { themeColor(with: "confirmBackground") }
    static var confirmText: ThemeColorPicker? { themeColor(with: "confirmText") }
    static var cancelBackground: ThemeColorPicker? { themeColor(with: "cancelBackground") }
}

//MARK: - Loading 颜色配置
public extension TDD_UIProvider.Loading {
    static var background: ThemeColorPicker? { themeColor(with: "background") }
    static var topBallBackground: ThemeColorPicker? { themeColor(with: "topBallBackground") }
    static var bottomBallBackground: ThemeColorPicker? { themeColor(with: "bottomBallBackground") }
}

// MARK: - UIColor Convenience Accessors
public extension UIColor {
    
    // General 相关属性
    @objc static var tdd_General_line: UIColor? { TDD_UIProvider.General.line?.color }
    @objc static var tdd_General_viewBorder: UIColor? { TDD_UIProvider.General.viewBorder?.color }
    @objc static var tdd_General_cardBackground: UIColor? { TDD_UIProvider.General.cardBackground?.color }
    @objc static var tdd_General_buttonBackground: UIColor? { TDD_UIProvider.General.buttonBackground?.color }
    @objc static var tdd_General_dashLine: UIColor? { TDD_UIProvider.General.dashLine?.color }
    @objc static var tdd_General_shadowBackground: UIColor? { TDD_UIProvider.General.shadowBackground?.color }
    @objc static var tdd_General_webLinkText: UIColor? { TDD_UIProvider.General.webLinkText?.color }
    @objc static var tdd_General_cellHeadBackground: UIColor? { TDD_UIProvider.General.cellHeadBackground?.color }
    @objc static var tdd_General_cellBackground: UIColor? { TDD_UIProvider.General.cellBackground?.color }
    @objc static var tdd_General_textFieldBackground: UIColor? { TDD_UIProvider.General.textFieldBackground?.color }
    @objc static var tdd_General_textFieldClearButtonTint: UIColor? { TDD_UIProvider.General.textFieldClearButtonTint?.color }
    @objc static var tdd_General_titleLock: UIColor? { TDD_UIProvider.General.titleLock?.color }
    @objc static var tdd_General_placeholderText: UIColor? { TDD_UIProvider.General.placeholderText?.color }
    @objc static var tdd_General_diagBlue: UIColor? { TDD_UIProvider.General.diagBlue?.color }
    @objc static var tdd_General_collectionViewBackground: UIColor? { TDD_UIProvider.General.collectionViewBackground?.color }
    
    // MsgProgress 相关属性
    @objc static var tdd_MsgProgress_titleText: UIColor? { TDD_UIProvider.MsgProgress.titleText?.color }
    @objc static var tdd_MsgProgress_trackTint: UIColor? { TDD_UIProvider.MsgProgress.trackTint?.color }
    @objc static func tdd_MsgProgress_progressTint(size: CGSize) -> UIColor? {
        TDD_UIProvider.MsgProgress.progressTint(size: size)?.color
    }
    @objc static var tdd_MsgProgress_progressTint: UIColor? { TDD_UIProvider.MsgProgress.progressTint?.color }
    
    // TopView 相关属性
    @objc static var tdd_TopView_tipsBackground: UIColor? { TDD_UIProvider.TopView.tipsBackground?.color }
    @objc static var tdd_TopView_tipsText: UIColor? { TDD_UIProvider.TopView.tipsText?.color }
    
    // BottomView 相关属性
    @objc static var tdd_BottomView_background: UIColor? { TDD_UIProvider.BottomView.background?.color }
    @objc static var tdd_BottomView_tipsBackground: UIColor? { TDD_UIProvider.BottomView.tipsBackground?.color }
    @objc static var tdd_BottomView_tipsText: UIColor? { TDD_UIProvider.BottomView.tipsText?.color }
    @objc static var tdd_BottomView_buttonNormalBackground: UIColor? { TDD_UIProvider.BottomView.buttonNormalBackground?.color }
    @objc static var tdd_BottomView_buttonDisableBackground: UIColor? { TDD_UIProvider.BottomView.buttonDisableBackground?.color }
    @objc static var tdd_BottomView_buttonHighlightBackground: UIColor? { TDD_UIProvider.BottomView.buttonHighlightBackground?.color }
    @objc static var tdd_BottomView_buttonNormalText: UIColor? { TDD_UIProvider.BottomView.buttonNormalText?.color }
    @objc static var tdd_BottomView_buttonDisableText: UIColor? { TDD_UIProvider.BottomView.buttonDisableText?.color }
    
    // Report 相关属性
    @objc static var tdd_Report_inputNormalCellBackground: UIColor? { TDD_UIProvider.Report.inputNormalCellBackground?.color }
    @objc static var tdd_Report_codeSectionText: UIColor? { TDD_UIProvider.Report.codeSectionText?.color }
    @objc static var tdd_Report_codeSectionBackground: UIColor? { TDD_UIProvider.Report.codeSectionBackground?.color }
    @objc static var tdd_Report_codeTitleText: UIColor? { TDD_UIProvider.Report.codeTitleText?.color }
    @objc static var tdd_Report_infoValueText: UIColor? { TDD_UIProvider.Report.infoValueText?.color }
    @objc static var tdd_Report_repairHeaderText: UIColor? { TDD_UIProvider.Report.repairHeaderText?.color }
    @objc static var tdd_Report_repairSectionPDFLine: UIColor? { TDD_UIProvider.Report.repairSectionPDFLine?.color }
    @objc static var tdd_Report_summaryBackground: UIColor? { TDD_UIProvider.Report.summaryBackground?.color }
    @objc static var tdd_Report_summaryPDFBackground: UIColor? { TDD_UIProvider.Report.summaryPDFBackground?.color }
    @objc static var tdd_Report_summaryBottomLine: UIColor? { TDD_UIProvider.Report.summaryBottomLine?.color }
    @objc static var tdd_Report_summaryTipsText: UIColor? { TDD_UIProvider.Report.summaryTipsText?.color }
    @objc static var tdd_Report_mileSelectBackground: UIColor? { TDD_UIProvider.Report.mileSelectBackground?.color }
    @objc static var tdd_Report_mileNormalBackground: UIColor? { TDD_UIProvider.Report.mileNormalBackground?.color }
    @objc static var tdd_Report_headCellBackground: UIColor? { TDD_UIProvider.Report.headCellBackground?.color }
    @objc static var tdd_Report_disclaimText: UIColor? { TDD_UIProvider.Report.disclaimText?.color }
    @objc static var tdd_Report_background: UIColor? { TDD_UIProvider.Report.background?.color }
    @objc static var tdd_Report_PDFBackground: UIColor? { TDD_UIProvider.Report.PDFBackground?.color }
    
    // SystemScan 相关属性
    @objc static var tdd_SystemScan_viewBackground: UIColor? { TDD_UIProvider.SystemScan.viewBackground?.color }
    @objc static var tdd_SystemScan_cellBackground: UIColor? { TDD_UIProvider.SystemScan.cellBackground?.color }
    @objc static var tdd_SystemScan_line: UIColor? { TDD_UIProvider.SystemScan.line?.color }
    @objc static func tdd_SystemScan_cellHighlightBackground(size: CGSize) -> UIColor? {
        TDD_UIProvider.SystemScan.cellHighlightBackground(size: size)?.color
    }
    @objc static var tdd_SystemScan_cellHighlightBackground: UIColor? { TDD_UIProvider.SystemScan.cellHighlightBackground?.color }
    
    // List 相关属性
    @objc static var tdd_List_background: UIColor? { TDD_UIProvider.List.background?.color }
    @objc static func tdd_List_cellSelectBackground(size: CGSize) -> UIColor? {
        TDD_UIProvider.List.cellSelectBackground(size: size)?.color
    }
    @objc static var tdd_List_cellSelectBackground: UIColor? { TDD_UIProvider.List.cellSelectBackground?.color }
    @objc static func tdd_List_cellHighlightBackground(size: CGSize) -> UIColor? {
        TDD_UIProvider.List.cellHighlightBackground(size: size)?.color
    }
    @objc static var tdd_List_cellHighlightBackground: UIColor? { TDD_UIProvider.List.cellHighlightBackground?.color }
    
    // LiveData 相关属性
    @objc static var tdd_LiveData_cellBackground: UIColor? { TDD_UIProvider.LiveData.cellBackground?.color }
    @objc static var tdd_LiveData_sepLine: UIColor? { TDD_UIProvider.LiveData.sepLine?.color }
    @objc static var tdd_LiveData_valueNormalText: UIColor? { TDD_UIProvider.LiveData.valueNormalText?.color }
    @objc static var tdd_LiveData_unitNormalText: UIColor? { TDD_UIProvider.LiveData.unitNormalText?.color }
    @objc static var tdd_LiveData_segmentBackground: UIColor? { TDD_UIProvider.LiveData.segmentBackground?.color }
    @objc static var tdd_LiveData_recordBackground: UIColor? { TDD_UIProvider.LiveData.recordBackground?.color }
    @objc static var tdd_LiveData_scoreText: UIColor? { TDD_UIProvider.LiveData.scoreText?.color }
    @objc static var tdd_LiveData_setBackground: UIColor? { TDD_UIProvider.LiveData.setBackground?.color }
    @objc static var tdd_LiveData_setRangeText: UIColor? { TDD_UIProvider.LiveData.setRangeText?.color }
    @objc static var tdd_LiveData_setRangeBackground: UIColor? { TDD_UIProvider.LiveData.setRangeBackground?.color }
    @objc static var tdd_LiveData_legendText: UIColor? { TDD_UIProvider.LiveData.legendText?.color }
    
    // DTC 相关属性
    @objc static var tdd_DTC_fault: UIColor? { TDD_UIProvider.DTC.fault?.color }
    @objc static var tdd_DTC_noFault: UIColor? { TDD_UIProvider.DTC.noFault?.color }
    @objc static var tdd_DTC_statusNormal: UIColor? { TDD_UIProvider.DTC.statusNormal?.color }
    @objc static var tdd_DTC_pdfStatsuNormal: UIColor? { TDD_UIProvider.DTC.pdfStatsuNormal?.color }
    @objc static var tdd_DTC_pdfNormal: UIColor? { TDD_UIProvider.DTC.pdfNormal?.color }
    
    // Keyboard 相关属性
    @objc static var tdd_Keyboard_background: UIColor? { TDD_UIProvider.Keyboard.background?.color }
    @objc static var tdd_Keyboard_itemDisableBackground: UIColor? { TDD_UIProvider.Keyboard.itemDisableBackground?.color }
    @objc static var tdd_Keyboard_itemNormalBackground: UIColor? { TDD_UIProvider.Keyboard.itemNormalBackground?.color }
    @objc static var tdd_Keyboard_itemHighlightBackground: UIColor? { TDD_UIProvider.Keyboard.itemHighlightBackground?.color }
    @objc static var tdd_Keyboard_itemNormalText: UIColor? { TDD_UIProvider.Keyboard.itemNormalText?.color }
    @objc static var tdd_Keyboard_itemHighlightBorder: UIColor? { TDD_UIProvider.Keyboard.itemHighlightBorder?.color }
    @objc static var tdd_Keyboard_itemDisableText: UIColor? { TDD_UIProvider.Keyboard.itemDisableText?.color }
    @objc static var tdd_Keyboard_enterBackground: UIColor? { TDD_UIProvider.Keyboard.enterBackground?.color }
    @objc static var tdd_Keyboard_deleteBackground: UIColor? { TDD_UIProvider.Keyboard.deleteBackground?.color }
    
    // Menu 相关属性
    @objc static var tdd_Menu_cellBackground: UIColor? { TDD_UIProvider.Menu.cellBackground?.color }
    @objc static var tdd_Menu_cellBackgroundGradientStyle: UIColor? { TDD_UIProvider.Menu.cellBackgroundGradientStyle?.color }
    @objc static var tdd_Menu_cellBackgroundGradientColors: UIColor? { TDD_UIProvider.Menu.cellBackgroundGradientColors?.color }
    @objc static var tdd_Menu_cellHighlightBackground: UIColor? { TDD_UIProvider.Menu.cellHighlightBackground?.color }
    @objc static var tdd_Menu_textDisable: UIColor? { TDD_UIProvider.Menu.textDisable?.color }
    
    // Popup 相关属性
    @objc static var tdd_Popup_background: UIColor? { TDD_UIProvider.Popup.background?.color }
    
    // Input 相关属性
    @objc static var tdd_Input_historyCellBackground: UIColor? { TDD_UIProvider.Input.historyCellBackground?.color }
    @objc static var tdd_Input_textViewBackground: UIColor? { TDD_UIProvider.Input.textViewBackground?.color }
    
    // Trouble 相关属性
    @objc static var tdd_Trouble_showStateBackground: UIColor? { TDD_UIProvider.Trouble.showStateBackground?.color }
    @objc static var tdd_Trouble_background: UIColor? { TDD_UIProvider.Trouble.background?.color }
    
    // FCA 相关属性
    @objc static var tdd_FCA_areaBackground: UIColor? { TDD_UIProvider.FCA.areaBackground?.color }
    
    // Alert 相关属性
    @objc static var tdd_Alert_background: UIColor? { TDD_UIProvider.Alert.background?.color }
    @objc static var tdd_Alert_confirmBackground: UIColor? { TDD_UIProvider.Alert.confirmBackground?.color }
    @objc static var tdd_Alert_confirmText: UIColor? { TDD_UIProvider.Alert.confirmText?.color }
    @objc static var tdd_Alert_cancelBackground: UIColor? { TDD_UIProvider.Alert.cancelBackground?.color }
    
    // Loading 相关属性
    @objc static var tdd_Loading_background: UIColor? { TDD_UIProvider.Loading.background?.color }
    @objc static var tdd_Loading_topBallBackground: UIColor? { TDD_UIProvider.Loading.topBallBackground?.color }
    @objc static var tdd_Loading_bottomBallBackground: UIColor? { TDD_UIProvider.Loading.bottomBallBackground?.color }
}

// MARK: - ThemeColorPicker Convenience Accessors
public extension ThemeColorPicker {
    
    // General 相关属性
    static var tdd_General_line: ThemeColorPicker? { TDD_UIProvider.General.line }
    static var tdd_General_viewBorder: ThemeColorPicker? { TDD_UIProvider.General.viewBorder }
    static var tdd_General_cardBackground: ThemeColorPicker? { TDD_UIProvider.General.cardBackground }
    static var tdd_General_buttonBackground: ThemeColorPicker? { TDD_UIProvider.General.buttonBackground }
    static var tdd_General_dashLine: ThemeColorPicker? { TDD_UIProvider.General.dashLine }
    static var tdd_General_shadowBackground: ThemeColorPicker? { TDD_UIProvider.General.shadowBackground }
    static var tdd_General_webLinkText: ThemeColorPicker? { TDD_UIProvider.General.webLinkText }
    static var tdd_General_cellHeadBackground: ThemeColorPicker? { TDD_UIProvider.General.cellHeadBackground }
    static var tdd_General_cellBackground: ThemeColorPicker? { TDD_UIProvider.General.cellBackground }
    static var tdd_General_textFieldBackground: ThemeColorPicker? { TDD_UIProvider.General.textFieldBackground }
    static var tdd_General_textFieldClearButtonTint: ThemeColorPicker? { TDD_UIProvider.General.textFieldClearButtonTint }
    static var tdd_General_titleLock: ThemeColorPicker? { TDD_UIProvider.General.titleLock }
    static var tdd_General_placeholderText: ThemeColorPicker? { TDD_UIProvider.General.placeholderText }
    static var tdd_General_diagBlue: ThemeColorPicker? { TDD_UIProvider.General.diagBlue }
    static var tdd_General_collectionViewBackground: ThemeColorPicker? { TDD_UIProvider.General.collectionViewBackground }
    
    // MsgProgress 相关属性
    static var tdd_MsgProgress_titleText: ThemeColorPicker? { TDD_UIProvider.MsgProgress.titleText }
    static var tdd_MsgProgress_trackTint: ThemeColorPicker? { TDD_UIProvider.MsgProgress.trackTint }
    static func tdd_MsgProgress_progressTint(size: CGSize) -> ThemeColorPicker? {
        TDD_UIProvider.MsgProgress.progressTint(size: size)
    }
    static var tdd_MsgProgress_progressTint: ThemeColorPicker? { TDD_UIProvider.MsgProgress.progressTint }
    
    // TopView 相关属性
    static var tdd_TopView_tipsBackground: ThemeColorPicker? { TDD_UIProvider.TopView.tipsBackground }
    static var tdd_TopView_tipsText: ThemeColorPicker? { TDD_UIProvider.TopView.tipsText }
    
    // BottomView 相关属性
    static var tdd_BottomView_background: ThemeColorPicker? { TDD_UIProvider.BottomView.background }
    static var tdd_BottomView_tipsBackground: ThemeColorPicker? { TDD_UIProvider.BottomView.tipsBackground }
    static var tdd_BottomView_tipsText: ThemeColorPicker? { TDD_UIProvider.BottomView.tipsText }
    static var tdd_BottomView_buttonNormalBackground: ThemeColorPicker? { TDD_UIProvider.BottomView.buttonNormalBackground }
    static var tdd_BottomView_buttonDisableBackground: ThemeColorPicker? { TDD_UIProvider.BottomView.buttonDisableBackground }
    static var tdd_BottomView_buttonHighlightBackground: ThemeColorPicker? { TDD_UIProvider.BottomView.buttonHighlightBackground }
    static var tdd_BottomView_buttonNormalText: ThemeColorPicker? { TDD_UIProvider.BottomView.buttonNormalText }
    static var tdd_BottomView_buttonDisableText: ThemeColorPicker? { TDD_UIProvider.BottomView.buttonDisableText }
    
    // Report 相关属性
    static var tdd_Report_inputNormalCellBackground: ThemeColorPicker? { TDD_UIProvider.Report.inputNormalCellBackground }
    static var tdd_Report_codeSectionText: ThemeColorPicker? { TDD_UIProvider.Report.codeSectionText }
    static var tdd_Report_codeSectionBackground: ThemeColorPicker? { TDD_UIProvider.Report.codeSectionBackground }
    static var tdd_Report_codeTitleText: ThemeColorPicker? { TDD_UIProvider.Report.codeTitleText }
    static var tdd_Report_infoValueText: ThemeColorPicker? { TDD_UIProvider.Report.infoValueText }
    static var tdd_Report_repairHeaderText: ThemeColorPicker? { TDD_UIProvider.Report.repairHeaderText }
    static var tdd_Report_repairSectionPDFLine: ThemeColorPicker? { TDD_UIProvider.Report.repairSectionPDFLine }
    static var tdd_Report_summaryBackground: ThemeColorPicker? { TDD_UIProvider.Report.summaryBackground }
    static var tdd_Report_summaryPDFBackground: ThemeColorPicker? { TDD_UIProvider.Report.summaryPDFBackground }
    static var tdd_Report_summaryBottomLine: ThemeColorPicker? { TDD_UIProvider.Report.summaryBottomLine }
    static var tdd_Report_summaryTipsText: ThemeColorPicker? { TDD_UIProvider.Report.summaryTipsText }
    static var tdd_Report_mileSelectBackground: ThemeColorPicker? { TDD_UIProvider.Report.mileSelectBackground }
    static var tdd_Report_mileNormalBackground: ThemeColorPicker? { TDD_UIProvider.Report.mileNormalBackground }
    static var tdd_Report_headCellBackground: ThemeColorPicker? { TDD_UIProvider.Report.headCellBackground }
    static var tdd_Report_disclaimText: ThemeColorPicker? { TDD_UIProvider.Report.disclaimText }
    static var tdd_Report_background: ThemeColorPicker? { TDD_UIProvider.Report.background }
    static var tdd_Report_PDFBackground: ThemeColorPicker? { TDD_UIProvider.Report.PDFBackground }
    
    // SystemScan 相关属性
    static var tdd_SystemScan_viewBackground: ThemeColorPicker? { TDD_UIProvider.SystemScan.viewBackground }
    static var tdd_SystemScan_cellBackground: ThemeColorPicker? { TDD_UIProvider.SystemScan.cellBackground }
    static var tdd_SystemScan_line: ThemeColorPicker? { TDD_UIProvider.SystemScan.line }
    static func tdd_SystemScan_cellHighlightBackground(size: CGSize) -> ThemeColorPicker? {
        TDD_UIProvider.SystemScan.cellHighlightBackground(size: size)
    }
    static var tdd_SystemScan_cellHighlightBackground: ThemeColorPicker? { TDD_UIProvider.SystemScan.cellHighlightBackground }
    
    // List 相关属性
    static var tdd_List_background: ThemeColorPicker? { TDD_UIProvider.List.background }
    static func tdd_List_cellSelectBackground(size: CGSize) -> ThemeColorPicker? {
        TDD_UIProvider.List.cellSelectBackground(size: size)
    }
    static var tdd_List_cellSelectBackground: ThemeColorPicker? { TDD_UIProvider.List.cellSelectBackground }
    static func tdd_List_cellHighlightBackground(size: CGSize) -> ThemeColorPicker? {
        TDD_UIProvider.List.cellHighlightBackground(size: size)
    }
    static var tdd_List_cellHighlightBackground: ThemeColorPicker? { TDD_UIProvider.List.cellHighlightBackground }
    
    // LiveData 相关属性
    static var tdd_LiveData_cellBackground: ThemeColorPicker? { TDD_UIProvider.LiveData.cellBackground }
    static var tdd_LiveData_sepLine: ThemeColorPicker? { TDD_UIProvider.LiveData.sepLine }
    static var tdd_LiveData_valueNormalText: ThemeColorPicker? { TDD_UIProvider.LiveData.valueNormalText }
    static var tdd_LiveData_unitNormalText: ThemeColorPicker? { TDD_UIProvider.LiveData.unitNormalText }
    static var tdd_LiveData_segmentBackground: ThemeColorPicker? { TDD_UIProvider.LiveData.segmentBackground }
    static var tdd_LiveData_recordBackground: ThemeColorPicker? { TDD_UIProvider.LiveData.recordBackground }
    static var tdd_LiveData_scoreText: ThemeColorPicker? { TDD_UIProvider.LiveData.scoreText }
    static var tdd_LiveData_setBackground: ThemeColorPicker? { TDD_UIProvider.LiveData.setBackground }
    static var tdd_LiveData_setRangeText: ThemeColorPicker? { TDD_UIProvider.LiveData.setRangeText }
    static var tdd_LiveData_setRangeBackground: ThemeColorPicker? { TDD_UIProvider.LiveData.setRangeBackground }
    static var tdd_LiveData_legendText: ThemeColorPicker? { TDD_UIProvider.LiveData.legendText }
    
    // DTC 相关属性
    static var tdd_DTC_fault: ThemeColorPicker? { TDD_UIProvider.DTC.fault }
    static var tdd_DTC_noFault: ThemeColorPicker? { TDD_UIProvider.DTC.noFault }
    static var tdd_DTC_statusNormal: ThemeColorPicker? { TDD_UIProvider.DTC.statusNormal }
    static var tdd_DTC_pdfStatsuNormal: ThemeColorPicker? { TDD_UIProvider.DTC.pdfStatsuNormal }
    static var tdd_DTC_pdfNormal: ThemeColorPicker? { TDD_UIProvider.DTC.pdfNormal }
    
    // Keyboard 相关属性
    static var tdd_Keyboard_background: ThemeColorPicker? { TDD_UIProvider.Keyboard.background }
    static var tdd_Keyboard_itemDisableBackground: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemDisableBackground }
    static var tdd_Keyboard_itemNormalBackground: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemNormalBackground }
    static var tdd_Keyboard_itemHighlightBackground: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemHighlightBackground }
    static var tdd_Keyboard_itemNormalText: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemNormalText }
    static var tdd_Keyboard_itemHighlightBorder: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemHighlightBorder }
    static var tdd_Keyboard_itemDisableText: ThemeColorPicker? { TDD_UIProvider.Keyboard.itemDisableText }
    static var tdd_Keyboard_enterBackground: ThemeColorPicker? { TDD_UIProvider.Keyboard.enterBackground }
    static var tdd_Keyboard_deleteBackground: ThemeColorPicker? { TDD_UIProvider.Keyboard.deleteBackground }
    
    // Menu 相关属性
    static var tdd_Menu_cellBackground: ThemeColorPicker? { TDD_UIProvider.Menu.cellBackground }
    static var tdd_Menu_cellBackgroundGradientStyle: ThemeColorPicker? { TDD_UIProvider.Menu.cellBackgroundGradientStyle }
    static var tdd_Menu_cellBackgroundGradientColors: ThemeColorPicker? { TDD_UIProvider.Menu.cellBackgroundGradientColors }
    static var tdd_Menu_cellHighlightBackground: ThemeColorPicker? { TDD_UIProvider.Menu.cellHighlightBackground }
    static var tdd_Menu_textDisable: ThemeColorPicker? { TDD_UIProvider.Menu.textDisable }
    
    // Popup 相关属性
    static var tdd_Popup_background: ThemeColorPicker? { TDD_UIProvider.Popup.background }
    
    // Input 相关属性
    static var tdd_Input_historyCellBackground: ThemeColorPicker? { TDD_UIProvider.Input.historyCellBackground }
    static var tdd_Input_textViewBackground: ThemeColorPicker? { TDD_UIProvider.Input.textViewBackground }
    
    // Trouble 相关属性
    static var tdd_Trouble_showStateBackground: ThemeColorPicker? { TDD_UIProvider.Trouble.showStateBackground }
    static var tdd_Trouble_background: ThemeColorPicker? { TDD_UIProvider.Trouble.background }
    
    // FCA 相关属性
    static var tdd_FCA_areaBackground: ThemeColorPicker? { TDD_UIProvider.FCA.areaBackground }
    
    // Alert 相关属性
    static var tdd_Alert_background: ThemeColorPicker? { TDD_UIProvider.Alert.background }
    static var tdd_Alert_confirmBackground: ThemeColorPicker? { TDD_UIProvider.Alert.confirmBackground }
    static var tdd_Alert_confirmText: ThemeColorPicker? { TDD_UIProvider.Alert.confirmText }
    static var tdd_Alert_cancelBackground: ThemeColorPicker? { TDD_UIProvider.Alert.cancelBackground }
    
    // Loading 相关属性
    static var tdd_Loading_background: ThemeColorPicker? { TDD_UIProvider.Loading.background }
    static var tdd_Loading_topBallBackground: ThemeColorPicker? { TDD_UIProvider.Loading.topBallBackground }
    static var tdd_Loading_bottomBallBackground: ThemeColorPicker? { TDD_UIProvider.Loading.bottomBallBackground }
}
