# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TopdonTechnology/Specs.git'
source 'http://172.16.50.23:8081/topdon-app/ios/specs.git'

target 'DiagExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'FMDB','2.7.5'
  pod 'YYModel', '1.0.4'
  pod 'SSZipArchive', '~> 2.4.2'
  pod 'Masonry','1.1.0'
  #pod 'Charts', '~> 3.6.0'
  pod 'YYText','1.0.7'
  pod "Texture",'3.1.0'
  pod 'Firebase/AnalyticsWithoutAdIdSupport','10.22.0'
  pod 'Firebase/Crashlytics','10.22.0'
  pod 'SocketRocket', '~> 0.6.0'
  pod 'YBImageBrowser','3.0.9'
  pod 'JHCampoCharts', '4.00.000'
  pod 'TDBasis', '5.00.022'
  pod 'SnapKit'
  pod 'TDUIProvider'

pod 'TopdonDiagnosis', :path => '../'
  # Pods for DiagExample

end
##FBRetainCycleDetector 错误修复
post_install do |installer|

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      xcconfig_path = config.base_configuration_reference.real_path
               xcconfig = File.read(xcconfig_path)
               xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
               File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
                                    
end
